server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: api
  
  datasource:
    username: sa
    password: SuperSecret
    url: jdbc:h2:mem:todoappdb
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.example.api.*: DEBUG
    

allowOrigins: "*"

filesPath: "temp/"
